import { describe, expect, it, vi } from 'vitest';
import { render, screen } from '@testing-library/react';
import RootLayout, { metadata } from './layout';

vi.mock('next/font/google', () => ({
  Geist: () => ({ variable: 'geist-sans' }),
  Geist_Mono: () => ({ variable: 'geist-mono' }),
}));

describe('RootLayout', () => {
  it('exports the expected page metadata', () => {
    expect(metadata).toEqual({
      title: 'Create Next App',
      description: 'Generated by create next app',
    });
  });

  it('renders its children', () => {
    render(
      <RootLayout>
        <p>child content</p>
      </RootLayout>
    );

    expect(screen.getByText('child content')).toBeInTheDocument();
  });
});
